<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OrigDocFetchServiceApp/OrigDocFetchService/FetchDocContent" name="FetchDocContent-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="FetchDocContent.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OrigDocFetchServiceApp/OrigDocFetchService/FetchDocContent"/>
    <wsdl:binding name="FetchDocContent_ptt-binding" type="fet:FetchDocContent_ptt" xmlns:fet="http://xmlns.oracle.com/pcbpel/adapter/db/OrigDocFetchServiceApp/OrigDocFetchService/FetchDocContent">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="FetchDocContentSelect">
            <soap:operation soapAction="FetchDocContentSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>