<wsdl:definitions name="FetchDocContent" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OrigDocFetchServiceApp/OrigDocFetchService/FetchDocContent" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OrigDocFetchServiceApp/OrigDocFetchService/FetchDocContent" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/FetchDocContent" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="FetchDocContent_plt">
    <plt:role name="FetchDocContent_role">
      <plt:portType name="tns:FetchDocContent_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/FetchDocContent" schemaLocation="FetchDocContent_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="FetchDocContentSelect_inputParameters">
        <wsdl:part name="FetchDocContentSelect_inputParameters" element="top:FetchDocContentSelect_id_name_versionInputParameters"/>
    </wsdl:message>
    <wsdl:message name="XCollection_msg">
        <wsdl:part name="XCollection" element="top:XCollection"/>
    </wsdl:message>
    <wsdl:portType name="FetchDocContent_ptt">
        <wsdl:operation name="FetchDocContentSelect">
            <wsdl:input message="tns:FetchDocContentSelect_inputParameters"/>
            <wsdl:output message="tns:XCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>